kill_signal = "SIGINT"
kill_timeout = 5
processes = []
region = "ams"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# optional if you want to change the PocketBase version
[build.args]
  PB_VERSION="0.19.3"
  MARMOT_VERSION="v0.8.6"

[[services]]
  http_checks          = []
  internal_port        = 8080
  processes            = ["app"]
  protocol             = "tcp"
  min_machines_running = 2
  auto_stop_machines   = false
  auto_start_machines  = true
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type       = "connections"

  [[services.ports]]
    force_https = true
    handlers    = ["http"]
    port        = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443

  [[services.tcp_checks]]
    grace_period  = "1s"
    interval      = "15s"
    restart_limit = 0
    timeout       = "2s"
