apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pocketbase-network-policy
  namespace: pocketbase
spec:
  podSelector: {}  # Selects all pods in the "pocketbase" namespace
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}  # Allows ingress traffic from any pod in the same namespace