apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-namespace-traffic
  namespace: pocketbase
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}