   apiVersion: rbac.authorization.k8s.io/v1
   kind: Role
   metadata:
     name: pocketbase-pod-reader
     namespace: pocketbase
   rules:
   - apiGroups: [""]
     resources: ["pods"]
     verbs: ["get", "list", "watch"]