apiVersion: rbac.authorization.k8s.io/v1
   kind: RoleBinding
   metadata:
     name: pocketbase-pod-reader-binding
     namespace: pocketbase
   subjects:
   - kind: ServiceAccount
     name: pocketbase  # Change if using a different ServiceAccount
   roleRef:
     kind: Role
     name: marmot-pod-reader
     apiGroup: rbac.authorization.k8s.io